const seed=[
 {id:'water',name:'Drink 2L water',icon:'⌁',color:'blue',days:[0,1,2,3,4,5,6],reminderTime:'09:00',logs:[],archived:false},
 {id:'read',name:'Read 20 pages',icon:'◒',color:'gold',days:[0,1,2,3,4,5,6],reminderTime:'20:30',logs:[],archived:false},
 {id:'workout',name:'Move my body',icon:'☼',color:'coral',days:[1,2,3,4,5],reminderTime:'07:00',logs:[],archived:false},
 {id:'sugar',name:'No added sugar',icon:'✦',color:'lilac',days:[0,1,2,3,4,5,6],reminderTime:'19:00',logs:[],archived:false},
 {id:'journal',name:'Write a few lines',icon:'♡',color:'green',days:[0,2,4,6],reminderTime:'21:00',logs:[],archived:true}
];
const colors={coral:'#ef7b63',gold:'#e9b94e',blue:'#72a9bb',lilac:'#9c8bb7',green:'#7ba982'};
const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
function localDay(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function sampleHabits(){let demo=structuredClone(seed),sampleDay=n=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return localDay(d)};demo[0].logs=Array.from({length:18},(_,n)=>sampleDay(n));demo[1].logs=Array.from({length:11},(_,n)=>sampleDay(n));demo[2].logs=Array.from({length:14},(_,n)=>{const d=new Date(sampleDay(n)+'T12:00:00');return d.getDay()>0&&d.getDay()<6?sampleDay(n):null}).filter(Boolean);demo[3].logs=Array.from({length:4},(_,n)=>sampleDay(n));return demo}
// Migrate the original single-user data once, then keep each person's data separate.
let profiles=JSON.parse(localStorage.getItem('daymark-profiles')||'null');
if(!profiles){let legacy=JSON.parse(localStorage.getItem('daymark-habits')||'null');profiles=[{id:crypto.randomUUID(),name:'Ananya',habits:legacy||sampleHabits(),challengeStart:localStorage.getItem('daymark-start')||localDay()}];localStorage.setItem('daymark-profiles',JSON.stringify(profiles))}
let activeProfileId=localStorage.getItem('daymark-active-profile')||profiles[0].id;
if(!profiles.some(p=>p.id===activeProfileId))activeProfileId=profiles[0].id;
let habits=profiles.find(p=>p.id===activeProfileId).habits;
let selectedDate=new Date(); selectedDate.setHours(0,0,0,0); let editing=null,filter='active';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function key(d){return localDay(d)} function dateFromKey(k){return new Date(k+'T12:00:00')}
function activeProfile(){return profiles.find(p=>p.id===activeProfileId)} function save(){activeProfile().habits=habits;localStorage.setItem('daymark-profiles',JSON.stringify(profiles));localStorage.setItem('daymark-active-profile',activeProfileId)}
function renderProfiles(){let profile=activeProfile();$('#profileName').textContent=profile.name;$('#profileInitial').textContent=profile.name.slice(0,1).toUpperCase();$('#profileList').innerHTML=profiles.map(p=>`<button class="profile-choice ${p.id===activeProfileId?'active':''}" data-profile="${p.id}"><span>${p.name.slice(0,1).toUpperCase()}</span>${p.name}${p.id===activeProfileId?'<small>Current</small>':''}</button>`).join('')}
function switchProfile(id){activeProfileId=id;habits=activeProfile().habits;filter='active';$('#allSearchInput').value='';save();renderProfiles();$('#profileDialog').close();renderToday();renderAll()}
function addProfile(name){let profile={id:crypto.randomUUID(),name,habits:[],challengeStart:localDay()};profiles.push(profile);activeProfileId=profile.id;habits=profile.habits;save();renderProfiles();$('#profileDialog').close();renderToday();renderAll()}
function todayDue(){let today=new Date();today.setHours(0,0,0,0);return habits.filter(h=>!h.archived&&scheduled(h,today)&&!logged(h,today))}
function renderMorningReminder(){let due=todayDue(),box=$('#morningReminder');if(!due.length){box.classList.add('hidden');return}let supported='Notification'in window,allowed=supported&&Notification.permission==='granted';box.classList.remove('hidden');box.innerHTML=`<div class="reminder-icon">☀</div><div class="reminder-copy"><strong>Morning check-in</strong><p>${due.length===1?`You still have ${due[0].name} to log today.`:`${due.length} habits are still waiting: ${due.slice(0,3).map(h=>h.name).join(', ')}${due.length>3?'…':''}`}</p></div>${allowed?'<span class="reminder-enabled">Alerts on</span>':supported?'<button class="reminder-button" data-enable-reminders>Enable reminder alerts</button>':''}`}
function maybeSendMorningReminder(){if(!('Notification'in window)||Notification.permission!=='granted')return;let now=new Date();if(now.getHours()<8||now.getHours()>=12)return;let due=todayDue();if(!due.length)return;let sent=JSON.parse(localStorage.getItem('daymark-morning-reminders')||'{}'),sentKey=`${activeProfileId}:${key(now)}`;if(sent[sentKey])return;new Notification('Daymark morning check-in',{body:due.length===1?`${due[0].name} is still waiting for you today.`:`${due.length} habits are still waiting for you today.`});sent[sentKey]=true;localStorage.setItem('daymark-morning-reminders',JSON.stringify(sent))}
function maybeSendHabitReminders(){if(!('Notification'in window)||Notification.permission!=='granted')return;let now=new Date(),today=key(now),minutes=now.getHours()*60+now.getMinutes(),sent=JSON.parse(localStorage.getItem('daymark-habit-reminders')||'{}');habits.filter(h=>!h.archived&&h.reminderTime&&scheduled(h,now)&&!logged(h,now)).forEach(h=>{let[hour,minute]=h.reminderTime.split(':').map(Number),reminderMinutes=hour*60+minute,sentKey=`${activeProfileId}:${h.id}:${today}`;if(minutes>=reminderMinutes&&!sent[sentKey]){new Notification(`Time for ${h.name}`,{body:`Did you complete ${h.name}? Open Daymark to tick it off.`});sent[sentKey]=true}});localStorage.setItem('daymark-habit-reminders',JSON.stringify(sent))}
function enableMorningAlerts(){if(!('Notification'in window))return;Notification.requestPermission().then(result=>{renderMorningReminder();if(result==='granted'){maybeSendMorningReminder();maybeSendHabitReminders()}})}
function scheduled(h,d){return h.days.includes(d.getDay())} function logged(h,d){return h.logs.includes(key(d))}
function streak(h){let d=new Date();d.setHours(0,0,0,0);if(!scheduled(h,d)||!logged(h,d))d.setDate(d.getDate()-1);let n=0;while(n<366){if(scheduled(h,d)){if(!logged(h,d))break;n++}d.setDate(d.getDate()-1)}return n}
function best(h){let logs=[...h.logs].sort(),best=0,cur=0,last=null;for(const k of logs){let d=dateFromKey(k);if(!scheduled(h,d))continue;if(last){let p=new Date(last);p.setDate(p.getDate()+1);while(!scheduled(h,p))p.setDate(p.getDate()+1);cur=key(p)===k?cur+1:1}else cur=1;best=Math.max(best,cur);last=k}return best}
function formatDate(d){return d.toLocaleDateString('en-US',{weekday:'long',day:'numeric',month:'long'})}function formatTime(time){if(!time)return'';let[hour,minute]=time.split(':');return new Date(2000,0,1,hour,minute).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}function scheduleLabel(h){return h.days.length===7?'Every day':h.days.length===5&&h.days.every(x=>x>0&&x<6)?'Weekdays':h.days.map(x=>dayNames[x]).join(' · ')}
function habitRow(h){let done=logged(h,selectedDate),s=streak(h),b=best(h),reminder=h.reminderTime?` · ⏰ ${formatTime(h.reminderTime)}`:'';return `<article class="habit ${done?'done':''}" style="--habit:${colors[h.color]}"><button class="check" data-toggle="${h.id}" aria-label="Mark ${h.name} complete">${done?'✓':''}</button><div class="habit-icon">${h.icon}</div><div class="habit-info"><div class="habit-name">${h.name}</div><div class="habit-schedule">${scheduleLabel(h)}${reminder} · Best: ${b} day${b===1?'':'s'}</div></div><div class="streak"><span class="flame">♨</span><b>${s}</b> day streak</div><button class="more" data-edit="${h.id}" aria-label="Edit ${h.name}">•••</button></article>`}
function renderToday(){let active=habits.filter(h=>!h.archived&&scheduled(h,selectedDate)),done=active.filter(h=>logged(h,selectedDate)).length;$('#dateHeading').textContent=formatDate(selectedDate);$('#greeting').textContent=selectedDate.toDateString()===new Date().toDateString()?`GOOD MORNING, ${activeProfile().name.toUpperCase()}`:'YOUR DAILY PLAN';$('#habitList').innerHTML=active.map(habitRow).join('');$('#emptyState').classList.toggle('hidden',active.length>0);$('#completedCount').textContent=done;$('#dueCount').textContent=active.length;$('#habitCount').textContent=`${active.length} habit${active.length===1?'':'s'} planned`;let ratio=active.length?done/active.length:0;$('#statusRing').style.borderTopColor=ratio===1?'#7ba982':'#ef7b63';$('#statusTitle').textContent=ratio===1&&active.length?'You did it!':'A fresh page.';$('#statusText').textContent=ratio===1&&active.length?'Every promise kept today.':'Start with one small win.';updateInsights();renderMorningReminder()}
function renderAll(){let q=$('#allSearchInput').value.toLowerCase(),list=habits.filter(h=>h.archived===(filter==='archived')&&h.name.toLowerCase().includes(q));$('#allHabitList').innerHTML=list.length?list.map(h=>`<article class="habit-card" style="--habit:${colors[h.color]}"><div class="habit-icon">${h.icon}</div><div class="habit-info"><div class="habit-name">${h.name} ${h.archived?'<span class="archived-tag">Archived</span>':''}</div><div class="habit-schedule">${scheduleLabel(h)}${h.reminderTime?` · ⏰ ${formatTime(h.reminderTime)}`:''} · <b>${streak(h)} day</b> current streak · Best ${best(h)}</div></div><div class="card-actions"><button class="mini-btn" data-edit="${h.id}" title="Edit">✎</button><button class="mini-btn" data-archive="${h.id}" title="${h.archived?'Restore':'Archive'}">${h.archived?'↶':'▣'}</button><button class="mini-btn delete-btn" data-delete="${h.id}" title="Delete permanently" aria-label="Delete ${h.name}">⌫</button></div></article>`).join(''):'<div class="empty-state"><div>⌕</div><h3>No habits found</h3><p>Try a different search.</p></div>'}
function updateInsights(){let active=habits.filter(h=>!h.archived),all=active.flatMap(h=>h.logs);$('#totalCompletions').textContent=all.length;let top=[...active].sort((a,b)=>streak(b)-streak(a))[0];$('#longestStreak').textContent=top?`${streak(top)} days`:'0 days';$('#longestName').textContent=top&&streak(top)?top.name:'Start a streak today';let dates=[...Array(7)].map((_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);d.setHours(0,0,0,0);return d}),rates=dates.map(d=>{let due=active.filter(h=>scheduled(h,d));return due.length?due.filter(h=>logged(h,d)).length/due.length:0});$('#weekRate').textContent=`${Math.round(rates.reduce((a,b)=>a+b,0)/7*100)}%`;$('#weekBars').innerHTML=dates.map((d,i)=>`<div class="day-bar"><i style="height:${30+rates[i]*55}px;--height:${rates[i]*100}%"></i>${dayNames[d.getDay()][0]}</div>`).join('');let n=Math.max(1,Math.min(75,Math.floor((new Date()-dateFromKey(activeProfile().challengeStart))/86400000)+1));$('#challengeDay').textContent=n;$('#challengeProgress').style.width=`${n/75*100}%`;renderHabitProgress(active)}
function renderHabitProgress(active){let today=new Date();today.setHours(0,0,0,0);let dates=Array.from({length:14},(_,i)=>{let d=new Date(today);d.setDate(d.getDate()-13+i);return d});$('#habitProgressList').innerHTML=active.length?active.map(h=>{let due=dates.filter(d=>scheduled(h,d)),completed=due.filter(d=>logged(h,d)),rate=due.length?Math.round(completed.length/due.length*100):0;let history=dates.map(d=>{let state=!scheduled(h,d)?'off':logged(h,d)?'done':'missed';return `<div class="history-day ${state}" title="${formatDate(d)}: ${state==='done'?'Done':state==='missed'?'Missed':'Not scheduled'}"><b>${d.toLocaleDateString('en-US',{weekday:'narrow'})}</b><i></i></div>`}).join('');let chart=dates.map(d=>{let state=!scheduled(h,d)?'off':logged(h,d)?'completed':'missed';let height=state==='completed'?48:state==='missed'?20:7;return `<i class="${state}" style="height:${height}px" title="${formatDate(d)}"></i>`}).join('');return `<article class="progress-card" style="--habit:${colors[h.color]}"><div class="progress-card-top"><div class="habit-icon">${h.icon}</div><div class="progress-card-title"><strong>${h.name}</strong><span>${streak(h)} day current streak · ${best(h)} day best streak</span></div><div class="progress-score"><strong>${rate}%</strong><span>14-day completion</span></div></div><div class="history-grid">${history}</div><div class="mini-chart">${chart}</div><div class="chart-note"><span>14 days ago</span><span>Today</span></div></article>`}).join(''):'<div class="empty-state"><div>✦</div><h3>No active habits yet</h3><p>Add a habit to see its progress.</p></div>'}
function toggle(id){let h=habits.find(x=>x.id===id),k=key(selectedDate);h.logs=h.logs.includes(k)?h.logs.filter(x=>x!==k):[...h.logs,k];save();renderToday();renderAll()}
function openDialog(id=null){editing=id;let h=id&&habits.find(x=>x.id===id);$('#dialogHeading').textContent=h?'Edit habit':'Create a new habit';$('#habitName').value=h?.name||'';$('#habitIcon').value=h?.icon||'☼';$('#habitColor').value=h?.color||'coral';$('#habitReminderTime').value=h?.reminderTime||'';$$('#scheduleDays button').forEach(b=>b.classList.toggle('selected',(h?.days||[1,2,3,4,5,6,0]).includes(+b.dataset.day)));$('#habitDialog').showModal()}
function saveHabit(){let name=$('#habitName').value.trim(),days=$$('#scheduleDays .selected').map(b=>+b.dataset.day);if(!name||!days.length)return;let h=editing?habits.find(x=>x.id===editing):{id:crypto.randomUUID(),logs:[],archived:false};Object.assign(h,{name,days,icon:$('#habitIcon').value,color:$('#habitColor').value,reminderTime:$('#habitReminderTime').value});if(!editing)habits.unshift(h);save();$('#habitDialog').close();renderToday();renderAll()}
document.addEventListener('click',e=>{let toggleBtn=e.target.closest('[data-toggle]'),edit=e.target.closest('[data-edit]'),archive=e.target.closest('[data-archive]'),del=e.target.closest('[data-delete]');if(toggleBtn)toggle(toggleBtn.dataset.toggle);if(edit)openDialog(edit.dataset.edit);if(archive){let h=habits.find(x=>x.id===archive.dataset.archive);h.archived=!h.archived;save();renderToday();renderAll()}if(del){let h=habits.find(x=>x.id===del.dataset.delete);if(h&&confirm(`Delete “${h.name}” permanently?\n\nThis also removes its completion history and streaks for ${activeProfile().name}.`)){habits=habits.filter(x=>x.id!==h.id);save();renderToday();renderAll()}}if(e.target.matches('#addHabit,#addHabit2'))openDialog();if(e.target.matches('#prevDay')){selectedDate.setDate(selectedDate.getDate()-1);renderToday()}if(e.target.matches('#nextDay')){selectedDate.setDate(selectedDate.getDate()+1);renderToday()}if(e.target.matches('#todayButton')){selectedDate=new Date();selectedDate.setHours(0,0,0,0);renderToday()}if(e.target.matches('.nav-link')){let v=e.target.dataset.view;$$('.nav-link').forEach(x=>x.classList.toggle('active',x===e.target));$$('.content').forEach(x=>x.classList.add('hidden'));$(`#${v}View`).classList.remove('hidden');if(v==='habits')renderAll();if(v==='insights')updateInsights()}if(e.target.matches('.filter')){filter=e.target.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===e.target));renderAll()}if(e.target.closest('#scheduleDays button'))e.target.closest('button').classList.toggle('selected')});
$('#habitForm').addEventListener('submit',e=>{if(e.submitter?.id==='saveHabit'){e.preventDefault();saveHabit()}});$('#searchInput').addEventListener('input',e=>{let v=e.target.value;$('.nav-link[data-view="habits"]').click();$('#allSearchInput').value=v;renderAll()});$('#allSearchInput').addEventListener('input',renderAll);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});document.addEventListener('click',e=>{if(e.target.closest('#profileButton')){$('#profileDialog').showModal();renderProfiles()}let choice=e.target.closest('[data-profile]');if(choice)switchProfile(choice.dataset.profile);if(e.target.closest('#closeProfiles'))$('#profileDialog').close();if(e.target.closest('[data-enable-reminders]'))enableMorningAlerts()});$('#profileForm').addEventListener('submit',e=>{e.preventDefault();let name=$('#newProfileName').value.trim();if(name){addProfile(name);$('#newProfileName').value=''}});renderProfiles();renderToday();maybeSendMorningReminder();maybeSendHabitReminders();setInterval(()=>{maybeSendMorningReminder();maybeSendHabitReminders()},30000);
